/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hOZqFTzgJ6S
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import QRCode from "qrcode.react";

interface QRCodeComponentProps {
  nftData: any;
  metaData: any;
}

export function QRCodeComponent({ nftData, metaData }: QRCodeComponentProps) {
  console.log("nftData, metaData", nftData, metaData);
  // Generate QR code value (you can customize what data you want to encode)
  const qrValue = JSON.stringify({ nftData, metaData });

  return (
    <>
      <div className="flex flex-col items-center w-full min-h-screen bg-gray-100 max-w-6xl mx-auto px-36 sm:px-">
        <div className="flex flex-col items-center w-full p-4 mt-8 rounded-lg shadow-md">
          <div className="flex flex-col items-center w-full p-4 text-white rounded-t-lg">
            <h2 className="text-lg font-bold">MATCH INFO</h2>
          </div>
          <div className="w-full p-4">
            <p className="text-lg font-bold">{metaData.matchDate}</p>
            <p className="text-sm text-gray-500">{metaData.description}</p>
            <p className="text-lg font-semibold mt-2">{metaData.name}</p>
            <div className="flex items-center justify-between w-full p-4 mt-4 bg-gray-100 rounded-lg">
              <div>
                <p className="text-sm text-gray-500">Role</p>
                <p className="text-lg font-bold">{nftData[3]}</p>
              </div>
              <div>
                <p className="text-sm text-gray-500">Entry Gate</p>
                <p className="text-lg font-bold">{metaData?.entryGate}</p>
              </div>
              <div>
                <p className="text-sm text-gray-500">Seat</p>
                <p className="text-lg font-bold">{nftData[2]}</p>
              </div>
            </div>
            <div className="flex flex-col items-center w-full mt-4">
              <QRCode value={qrValue} size={150} className="w-40 h-40" />
              <p className="mt-8 text-sm text-gray-500">
                Please scan the QR code at the authentication machine.
              </p>
            </div>
            <div className="flex flex-col w-full mt-4 text-sm text-gray-500">
              <div className="flex justify-between">
                <span>Venue</span>
                <span className="font-bold text-right">
                  {metaData.stadiumName}
                </span>
              </div>
              <div className="flex justify-between mt-2">
                <span>Opening Time</span>
                <span className="font-bold text-right">
                  {metaData.openingTime}
                </span>
              </div>
              <div className="flex justify-between mt-2">
                <span>Kickoff Time</span>
                <span className="font-bold text-right">
                  {metaData.kickoffTime}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
